name: Learn
on:
  push:
    branches:
      - gh-pages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: learn workflows
        run: echo Hello build.yaml
      - run: echo 2
      - run: echo node -v
      - run: >
           apt install docker
           echo docker version
