name: Learn
on:
  push:
    branches:
      - gh-pages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: 测试if语句
        if: ${{ 1<2}}
        run: echo 1<2
#       - name: Set up Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: 20
#       - name: 输出测试一下
#         run: echo Hello build.yaml
#       - name: 安装docker服务
#         uses: docker-practice/actions-setup-docker@master
#         timeout-minutes: 12
#       - name: 输出node版本测试是否成功
#         run: node -v
#       - name: 测试docker是否安装
#         run: |
#           docker version
